spring.application.name=petalback

spring.datasource.url=jdbc:mysql://localhost:3306/petalpath?useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=P*****
spring.jpa.hibernate.ddl-auto=update